---
default_language_version:
  python: "python3"
fail_fast: false
ci:
  skip: ["poetry-lock", "lint", "mypy", "docs"]

repos:
  - repo: "https://github.com/pre-commit/pre-commit-hooks"
    rev: "v4.4.0"
    hooks:
      - id: "check-added-large-files"
      - id: "check-ast"
      - id: "check-byte-order-marker"
      - id: "check-docstring-first"
      - id: "check-executables-have-shebangs"
      - id: "check-json"
      - id: "check-symlinks"
      - id: "check-merge-conflict"
      - id: "check-vcs-permalinks"
      - id: "check-xml"
      - id: "check-yaml"
      - id: "debug-statements"
      - id: "end-of-file-fixer"
        exclude: ".+\\.ipynb"
      - id: "name-tests-test"
      - id: "trailing-whitespace"

  - repo: "https://github.com/pre-commit/pygrep-hooks"
    rev: "v1.10.0"
    hooks:
      - id: "python-check-blanket-noqa"
      - id: "python-check-blanket-type-ignore"
      - id: "python-use-type-annotations"

  - repo: "https://github.com/asottile/reorder_python_imports"
    rev: "v3.9.0"
    hooks:
      - id: "reorder-python-imports"
        args:
          - "--py38-plus"

  - repo: "https://github.com/psf/black"
    rev: "22.12.0"
    hooks:
      - id: "black"

  # - repo: "https://github.com/fpgmaas/deptry"
  #   rev: "0.7.1"
  #   hooks:
  #     - id: "deptry"
  #       args: ["--ignore-notebooks"]

  - repo: "https://github.com/python-poetry/poetry"
    rev: "1.3.0"
    hooks:
      - id: "poetry-check"
      - id: "poetry-lock"
      - id: "poetry-export"
        args: ["--without-hashes", "-f", "requirements.txt", "-o", "requirements/requirements.txt"]
      - id: "poetry-export"
        args: ["--without-hashes", "-f", "requirements.txt", "--dev", "-o", "requirements/requirements-dev.txt"]

  - repo: "local"
    hooks:

      - id: "lint"
        name: "lint"
        entry: "make lint"
        language: "system"
        types: ["python"]

      - id: "mypy"
        name: "mypy"
        entry: "make mypy"
        language: "system"
        types: ["python"]

      - id: "docs"
        name: "docs"
        entry: "make docs"
        language: "system"
